echo ""
echo ""
echo "Welcome to the fish"
echo "Please login to the supernova machine if you would like to reduce some data:"
echo "ssh -X {user}@supernova.science.lco.global"
echo ""
echo "Instructions can be found at https://www.authorea.com/users/75900/articles/96044-image-subtraction-with-lcogtsnpipe/_show_article"
echo ""
echo ""
